Infinite.MVCCore.TaxiBooking/Models/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Infinite.MVCCore.TaxiBooking.Models
{
    public class CustomerViewModel
    {
        public int CustomerId { get; set; }
        [Required(ErrorMessage ="Please provide name")]
        [Display(Name ="Customer Name")]
        public string CustomerName { get; set; }
        [Required(ErrorMessage ="Please provide Mobile Number")]
        [Phone]
        [Display(Name ="Mobile Number")]
        public string PhoneNo { get; set; }
        [Required(ErrorMessage ="Please provide Email Id")]
        [EmailAddress]
        [Display(Name ="Email Id")]
        public string EmailId { get; set; }
        [Required(ErrorMessage ="Please provide address")]
        public string Address { get; set; }
    }
}

Infinite.MVCCore.TaxiBooking/Models/EmployeeRosterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Infinite.MVCCore.TaxiBooking.Models
{
    public class EmployeeRosterViewModel
    {
        public int Id { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public DateTime InTime { get; set; }
        public DateTime OutTime { get; set; }
        public int EmployeeId { get; set; }
    }
}

Infinite.MVCCore.TaxiBooking/Models/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Infinite.MVCCore.TaxiBooking.Models
{
    public class EmployeeViewModel
    {
        public int EmployeeId { get; set; }
        [Required(ErrorMessage ="Please provide name")]
        [Display(Name ="Employee Name")]
        public string EmployeeName { get; set; }
        [Required(ErrorMessage ="Please provide destination")]
        public int DesignationId { get; set; }
        [Required(ErrorMessage ="Please provide Mobile Number")]
        [Display(Name ="Mobile Number")]
        public string PhoneNo { get; set; }
        [Required]
        [Display(Name ="Email Id")]
        public string EmailId { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        [Display(Name ="Driving License Number")]
        public string DrivingLicenseNo { get; set; }
        public List<DesignationViewModel> Designations { get; set; }
        public string DesignationName { get; set; }
    }
}

Infinite.MVCCore.TaxiBooking/Controllers/AdminController.cs
using Infinite.MVCCore.TaxiBooking.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace Infinite.MVCCore.TaxiBooking.Controllers
{
    public class AdminController : Controller
    {
        public readonly IConfiguration _configuration;
        public IActionResult Index()
        {
            return View();
        }

        public AdminController( IConfiguration configuration)
        {
            _configuration= configuration;
        }

        public async Task<IActionResult> Customers()
        {

            List<CustomerViewModel> customers = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("Customers/GetAllCustomers");
                if (result.IsSuccessStatusCode)
                {
                    customers = await result.Content.ReadAsAsync<List<CustomerViewModel>>();
                }
            }
            return View(customers);
           
        }
        public async Task<IActionResult> Employees()
        {
            List<EmployeeViewModel> employees = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("Employees/GetAllEmployees");
                if (result.IsSuccessStatusCode)
                {
                    employees = await result.Content.ReadAsAsync<List<EmployeeViewModel>>();
                }
            }
            return View(employees);
        }
        public async Task<IActionResult> EmployeeRoster()
        {
            List<EmployeeRosterViewModel> employeeRosters = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("EmployeeRosters/GetAllRosters");
                if (result.IsSuccessStatusCode)
                {
                    employeeRosters = await result.Content.ReadAsAsync<List<EmployeeRosterViewModel>>();
                }
            }

            return View(employeeRosters);
           
        }
    }
}

Infinite.MVCCore.TaxiBooking/Controllers/CustomersController.cs
using Infinite.MVCCore.TaxiBooking.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace Infinite.MVCCore.TaxiBooking.Controllers
{
    public class CustomersController : Controller
    {
        public readonly IConfiguration _configuration;
        public CustomersController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Landing()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
            List<CustomerViewModel> customers = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("Customers/GetAllCustomers");
                if (result.IsSuccessStatusCode)
                {
                    customers = await result.Content.ReadAsAsync<List<CustomerViewModel>>();
                }
            }
            return View(customers);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            CustomerViewModel customer = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync($"Customers/GetCustomerById/{id}");
                if (result.IsSuccessStatusCode)
                {
                    customer = await result.Content.ReadAsAsync<CustomerViewModel>();
                }
            }
            return View(customer);
        }

        [HttpGet]
        [Route("Customers/Create")]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost("Customers/Create")]
        public async Task<IActionResult> Create(CustomerViewModel customer)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    
                    var result = await client.PostAsJsonAsync("Customers/CreateCustomer", customer);
                    if (result.StatusCode == System.Net.HttpStatusCode.Created)
                    {

                        return RedirectToAction("Index");
                    }
                }
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (ModelState.IsValid)
            {
                CustomerViewModel customer = null;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.GetAsync($"Customers/GetCustomerById/{id}");
                    if (result.IsSuccessStatusCode)
                    {
                        customer = await result.Content.ReadAsAsync<CustomerViewModel>();
                        return View(customer);
                    }
                    else
                    {
                        ModelState.AddModelError("", "Customer doesn't exist");
                    }

                }
            }
            return View();
        }

        [HttpPost]
        [Route("Customers/Edit/{CustomerId}")]
        public async Task<IActionResult> Edit(CustomerViewModel customer)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.PutAsJsonAsync($"Customers/UpdateCustomer/{customer.CustomerId}", customer);
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Server Error, Please try later");
                    }

                }
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            CustomerViewModel customer = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync($"Customers/GetCustomerById/{id}");
                if (result.IsSuccessStatusCode)
                {
                    customer = await result.Content.ReadAsAsync<CustomerViewModel>();
                    return View(customer);
                }
                else
                {
                    ModelState.AddModelError("", "Server Error.Please try later");
                }
            }
            return View(customer);
        }



        [HttpPost("Customers/Delete/{CustomerId}")]
        public async Task<IActionResult> Delete(CustomerViewModel customer)
        {
            
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.DeleteAsync($"Customers/DeleteCustomer/{customer.CustomerId}");
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");

                }
                else
                {
                    ModelState.AddModelError("", "Server Error.Please try later");
                }
            }
            return View();

        }
    }
}

Infinite.MVCCore.TaxiBooking/Controllers/EmployeeRostersController.cs
using Infinite.MVCCore.TaxiBooking.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace Infinite.MVCCore.TaxiBooking.Controllers
{
    public class EmployeeRostersController : Controller
    {
        private readonly IConfiguration _configuration;

        public EmployeeRostersController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> Index()
        {
            List<EmployeeRosterViewModel> employeeRosters = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("EmployeeRosters/GetAllRosters");
                if (result.IsSuccessStatusCode)
                {
                    employeeRosters = await result.Content.ReadAsAsync<List<EmployeeRosterViewModel>>();
                }
            }

            return View(employeeRosters);
        }
        public async Task<IActionResult> Details(int id)
        {
            EmployeeRosterViewModel employeeRoster = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync($"EmployeeRosters/GetRosterById/{id}");
                if (result.IsSuccessStatusCode)
                {
                    employeeRoster = await result.Content.ReadAsAsync<EmployeeRosterViewModel>();
                }
            }
            return View(employeeRoster);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(EmployeeRosterViewModel employee)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.PostAsJsonAsync("EmployeeRosters/CreateRoster", employee);
                    if (result.StatusCode == System.Net.HttpStatusCode.Created)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View(employee);
        }

        [HttpGet]

        public async Task<IActionResult> Edit(int id)
        {
            if (ModelState.IsValid)
            {
                EmployeeRosterViewModel employee = null;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.GetAsync($"EmployeeRosters/GetRosterById/{id}");
                    if (result.IsSuccessStatusCode)
                    {
                        employee = await result.Content.ReadAsAsync<EmployeeRosterViewModel>();
                        return View(employee);
                    }
                    else
                    {
                        ModelState.AddModelError("", "Customer doesn't exist");
                    }

                }
            }
            return View();
        }

        [HttpPost]
        [Route("EmployeeRosters/Edit/{Id}")]
        public async Task<IActionResult> Edit(EmployeeRosterViewModel employee)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.PutAsJsonAsync($"EmployeeRosters/UpdateRoster/{employee.Id}", employee);
                    if (result.StatusCode == System.Net.HttpStatusCode.NoContent)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Server Error, Please try later");
                    }

                }
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            EmployeeRosterViewModel employee = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync($"EmployeeRosters/GetRosterById/{id}");
                if (result.IsSuccessStatusCode)
                {
                    employee = await result.Content.ReadAsAsync<EmployeeRosterViewModel>();
                    return View(employee);
                }
                else
                {
                    ModelState.AddModelError("", "Server Error.Please try later");
                    }
                }
                return View(employee);
        }

        [HttpPost]
        [Route("EmployeeRosters/Delete/{Id}")]
        public async Task<IActionResult> Delete(EmployeeRosterViewModel employee)
        {
            using (var client = new HttpClient())
            {
                //client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.DeleteAsync($"EmployeeRosters/DeleteRoster/{employee.Id}");
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Server Error.Please try later");
                }
            }
            return View(employee);
        }
    }
}

Infinite.MVCCore.TaxiBooking/Views/Admin/Customers.cshtml
@model IEnumerable<CustomerViewModel>
@{
    ViewData["Title"] = "Customers";
}

<h1>Index</h1>

<div class="row offset-2 pt-4">
    <div class="col-md-9">
        <a asp-controller="Customers" asp-action="Create" class="btn btn-info">Create</a>

        <table class="table table-hover border-2">
            <thead>
                <tr>

                    <th scope="col">Customer Id</th>
                    <th scope="col">  </th>
                    <th scope="col">  </th>
                    <th scope="col">Custmer Name</th>
                    <th scope="col">  </th>
                    <th scope="col">  </th>
                    <th scope="col" class="offset-2">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {


                    <tr class="table-dark">

                        <td>@item.CustomerId</td>
                        <td> </td>
                        <td></td>
                        <td>@item.CustomerName</td>
                        <td> </td>
                        <td></td>
                        <td class="pl-3">
                            <a asp-controller="Customers" asp-action="Details" asp-route-id="@item.CustomerId" class="btn btn-light">Details</a>
                            @*<a asp-controller="Customers" asp-action="Edit" asp-route-id="@item.CustomerId" class="btn btn-primary">Edit</a>
                            <a asp-controller="Customers" asp-action="Delete" asp-route-id="@item.CustomerId" class="btn btn-danger">Delete</a>*@
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>

Infinite.MVCCore.TaxiBooking/Views/Admin/EmployeeRoster.cshtml
@model IEnumerable<EmployeeRosterViewModel>
@{
    ViewData["Title"] = "EmployeeRoster";
}



<div class="row ">
    <div class="col">
        <div class="row pt-5">
            <div class="col">
                <h2>List of EmployeeRosters</h2>
            </div>
            <div class="col offset-6">
                <a asp-controller="EmployeeRosters" asp-action="Create" class="btn btn-primary">Create new EmployeeRosters</a>
            </div>

        </div>

        <div class="col">
            <table class="table table-hover col-md-8">
                <thead>
                    <tr>
                        <th>RosterId</th>
                        <th>FromDate</th>
                        <th>ToDate</th>
                        <th>InTime</th>
                        <th>OutTime</th>
                        <th>EmployeeId</th>
                        <th>Actions</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var x in Model)
                    {
                        <tr>
                            <td class="col-md-2">@x.Id</td>
                            <td class="col-md-2">@x.FromDate.ToShortDateString()</td>
                            <td class="col-md-2">@x.ToDate.ToShortDateString()</td>
                            <td class="col-md-2">@x.InTime.ToShortTimeString()</td>
                            <td class="col-md-2">@x.OutTime.ToShortTimeString()</td>
                            <td class="col-md-2">@x.EmployeeId</td>
                            <td class="col-md-9">
                                <a asp-controller="EmployeeRosters" asp-action="Details" asp-route-id="@x.Id" class="btn btn-primary">Details</a>
                                <a asp-controller="EmployeeRosters" asp-action="Edit" asp-route-id="@x.Id" class="btn btn-primary">Edit</a>
                                <a asp-controller="EmployeeRosters" asp-action="Delete" asp-route-id="@x.Id" class="btn btn-primary">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>
</div>

Infinite.MVCCore.TaxiBooking/Views/Admin/Employees.cshtml
@model IEnumerable<EmployeeViewModel>

@{
    ViewData["Title"] = "Employees";
}

<body class="image">

    <div class=" row pt-5 ">
        @*<div class="col-md-9">*@
        <div class="row">
            <div class="col">
                <h2>List of Employees</h2>
            </div>
            <div class="col">
                <a asp-controller="Employees" asp-action="Create" class="btn btn-primary">Create new Employee</a>
            </div>

        </div>

        <div class="col-md-9">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Employee Id</th>
                        <th>Employee Name</th>
                        @*<th>Designation</th>*@
                        <th>Action</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var x in Model)
                    {
                        <tr>
                            <td>@x.EmployeeId</td>
                            <td>@x.EmployeeName</td>
                            @*<td>@x.Designation</td>*@
                            <td>
                                <a asp-controller="Employees" asp-action="Details" asp-route-id="@x.EmployeeId" class="btn btn-primary">Details</a>
                                <a asp-controller="Employees" asp-action="Edit" asp-route-id="@x.EmployeeId" class="btn btn-primary">Edit</a>
                                <a asp-controller="Employees" asp-action="Delete" asp-route-id="@x.EmployeeId" class="btn btn-primary">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
        @*</div>*@
    </div>
</body>

<style>
    .image {
        background-image: url("https://media.giphy.com/media/idqBjf5wngkDJMtlIg/giphy.gif");
        background-repeat:no-repeat;
        background-size:cover;
    }
</style>

Infinite.MVCCore.TaxiBooking/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<a asp-controller="Admin" asp-action="Customers" class="btn btn-info">Customer Details</a>
<a asp-controller="Admin" asp-action="Employees" class="btn btn-danger">Employee Details</a>
<a asp-controller="Admin" asp-action="EmployeeRoster" class="btn btn-danger">EmployeeRoster Details</a>