Infinite.MVCCore.TaxiBooking/Models/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Infinite.MVCCore.TaxiBooking.Models
{
    public class EmployeeViewModel
    {
        public int EmployeeId { get; set; }
        [Required(ErrorMessage ="Please provide name")]
        [Display(Name ="Employee Name")]
        public string EmployeeName { get; set; }
        [Required(ErrorMessage ="Please provide destination")]
        public int DesignationId { get; set; }
        [Required(ErrorMessage ="Please provide Mobile Number")]
        [Display(Name ="Mobile Number")]
        public string PhoneNo { get; set; }
        [Required]
        [Display(Name ="Email Id")]
        public string EmailId { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        [Display(Name ="Driving License Number")]
        public string DrivingLicenseNo { get; set; }
        public List<DesignationViewModel> Designations { get; set; }
        public string DesignationName { get; set; }
    }
}

Infinite.MVCCore.TaxiBooking/Controllers/AdminController.cs
using Infinite.MVCCore.TaxiBooking.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace Infinite.MVCCore.TaxiBooking.Controllers
{
    public class AdminController : Controller
    {
        public readonly IConfiguration _configuration;
        public IActionResult Index()
        {
            return View();
        }

        public AdminController( IConfiguration configuration)
        {
            _configuration= configuration;
        }

        public async Task<IActionResult> Customers()
        {

            List<CustomerViewModel> customers = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("Customers/GetAllCustomers");
                if (result.IsSuccessStatusCode)
                {
                    customers = await result.Content.ReadAsAsync<List<CustomerViewModel>>();
                }
            }
            return View(customers);
           
        }
        public async Task<IActionResult> Employees()
        {
            List<EmployeeViewModel> employees = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("Employees/GetAllEmployees");
                if (result.IsSuccessStatusCode)
                {
                    employees = await result.Content.ReadAsAsync<List<EmployeeViewModel>>();
                }
            }
            return View(employees);
        }
        public async Task<IActionResult> EmployeeRoster()
        {
            List<EmployeeRosterViewModel> employeeRosters = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("EmployeeRosters/GetAllRosters");
                if (result.IsSuccessStatusCode)
                {
                    employeeRosters = await result.Content.ReadAsAsync<List<EmployeeRosterViewModel>>();
                }
            }

            return View(employeeRosters);
           
        }
    }
}

Infinite.MVCCore.TaxiBooking/Controllers/EmployeesController.cs
using Infinite.MVCCore.TaxiBooking.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace Infinite.MVCCore.TaxiBooking.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly IConfiguration _configuration;

        public EmployeesController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Landing()
        {
            return View();
        }
        public async Task<IActionResult> Index()
        {
            List<EmployeeViewModel> employees = new();
            using(var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("Employees/GetAllEmployees");
                if (result.IsSuccessStatusCode)
                {
                    employees = await result.Content.ReadAsAsync<List<EmployeeViewModel>>();
                }
            }
            return View(employees);
        }

        public async Task<IActionResult> Details(int id)
        {
            EmployeeViewModel employee = null;
            using(var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync($"Employees/GetEmployeeById/{id}");
                if (result.IsSuccessStatusCode)
                {
                    employee = await result.Content.ReadAsAsync<EmployeeViewModel>();
                }
            }
            return View(employee);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            EmployeeViewModel viewModel = new EmployeeViewModel
            {
                Designations = await this.GetDesignations()
            };
            return View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Create(EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                using(var client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.PostAsJsonAsync("Employees/CreateEmployee", employee);
                    if (result.StatusCode == System.Net.HttpStatusCode.Created)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            EmployeeViewModel viewModel = new EmployeeViewModel
            {
                Designations = await this.GetDesignations()
            };
            return View(viewModel);
          
        }
        [HttpGet]

        public async Task<IActionResult> Edit(int id)
        {
            if (ModelState.IsValid)
            {
                EmployeeViewModel employee = null;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.GetAsync($"Employees/GetEmployeeById/{id}");
                    if (result.IsSuccessStatusCode)
                    {
                        employee = await result.Content.ReadAsAsync<EmployeeViewModel>();
                        return View(employee);
                    }
                    //else
                    //{
                    //    //ModelState.AddModelError("", "Customer doesn't exist");
                    //}

                }
            }
            return View();
        }

        [HttpPost]
        [Route("Employees/Edit/{EmployeeId}")]
        public async Task<IActionResult> Edit(EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.PutAsJsonAsync($"Employees/UpdateEmployee/{employee.EmployeeId}", employee);
                    if (result.StatusCode == System.Net.HttpStatusCode.NoContent)
                    {
                        return RedirectToAction("Index");
                    }
                    //else
                    //{
                    //    ModelState.AddModelError("", "Server Error, Please try later");
                    //}

                }
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            EmployeeViewModel employee = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync($"Employees/GetEmployeeById/{id}");
                if (result.IsSuccessStatusCode)
                {
                    employee = await result.Content.ReadAsAsync<EmployeeViewModel>();
                    return View(employee);
                }
                else
                {
                    ModelState.AddModelError("", "Server Error.Please try later");
                }
            }
            return View(employee);
        }

        [HttpPost]
        [Route("Employees/Delete/{EmployeeId}")]
        public async Task<IActionResult> Delete(EmployeeViewModel employee)
        {
            using (var client = new HttpClient())
            {
                //client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.DeleteAsync($"Employees/DeleteEmployee/{employee.EmployeeId}");
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Server Error.Please try later");
                }
            }
            return View();
        }
      [NonAction]
      public async Task<List<DesignationViewModel>> GetDesignations()
        {
            List<DesignationViewModel> designations = new();
            using(var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("Employees/GetDesignations");
                if (result.IsSuccessStatusCode)
                {
                    designations = await result.Content.ReadAsAsync<List<DesignationViewModel>>();
                }

            }
            return designations;
        }

        
       

    }
}

Infinite.MVCCore.TaxiBooking/Views/Employees/Create.cshtml
@model EmployeeViewModel
@{
    ViewData["Title"] = "Create";
}

<style>
    .image {
        background-image: url('https://images.unsplash.com/photo-1516733968668-dbdce39c4651?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8VGF4aXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60');
        background-size: cover;
        background-repeat: no-repeat;
    }

    .setting{
        margin-left:400px;
    }
</style>
<body class="image text-black">
    <div class="container pt-5">
        <h1 class="setting">Create An Employee</h1>
        <form asp-controller="Employees" asp-action="Create" method="post">
            <div class="row setting">
                <div class="col-md-6">
                    <div class="md-2">
                        <label asp-for="EmployeeName" class="form-label"></label>
                        <input type="text" asp-for="EmployeeName" class="form-control" />
                        <span asp-validation-for="EmployeeName"></span>
                    </div>

                    <div class="mb-2">
                        <label asp-for="DesignationId" class="form-label"></label>
                        <select asp-for="DesignationId" asp-items="@(new SelectList(Model.Designations,"Id","DesignationName"))" class="form-select">
                            <option value="">---Select---</option>
                        </select>
                        <span asp-validation-for="DesignationId"></span>
                    </div>

                    <div class="mb-2">
                        <label asp-for="PhoneNo" class="form-label"></label>
                        <input type="text" asp-for="PhoneNo" class="form-control" />
                        <span asp-validation-for="PhoneNo"></span>
                    </div>

                    <div class="mb-2">
                        <label asp-for="EmailId" class="form-label"></label>
                        <input type="text" asp-for="EmailId" class="form-control"/>
                        <span asp-validation-for="EmailId"></span>
                    </div>

                    <div class="mb-2">
                        <label asp-for="Address" class="form-label"></label>
                        <input type="text" asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address"></span>
                    </div>

                    <div class="mb-2">
                        <label asp-for="DrivingLicenseNo" class="form-label"></label>
                        <input type="text" asp-for="DrivingLicenseNo" class="form-control" />
                        <span asp-validation-for="DrivingLicenseNo"></span>
                    </div>

                    <div class="mt-2 d-grid">
                        <input type="submit" class="btn btn-primary" value="Add New" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</body>

Infinite.MVCCore.TaxiBooking/Views/Employees/Delete.cshtml
@model EmployeeViewModel
@{
    ViewData["Title"] = "Delete";
}
<body>
    <div class="container offset-4 pt-5">
        <h1>Delete Employee</h1>

        <div class="row">
            <div class="col-md-5">
                @*<div asp-validation-summary=""></div>*@
                <ul class="list-group">
                    <li class="list-group-item"><b>Employee Name :</b> @Model.EmployeeName</li>
                    <li class="list-group-item"><b>Designation:</b>@Model.DesignationId</li>
                    <li class="list-group-item"><b>Phone NO :</b>oModel.PhoneNo</li>
                    <li class="list-group-item"><b>Email Id :</b>@Model.EmailId</li>
                    <li class="list-group-item"><b>Address :</b>@Model.Address</li>
                    <li class="list-group-item"><b>Driving LicenceNo :</b>@Model.DrivingLicenseNo</li>
                </ul>
                <div>
                    Are sure do you want to delete this Employee?
                </div>
                <div>
                    <form asp-controller="Employees" asp-action="Delete" method="post">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>

                <a asp-controller="Movies" asp-action="Index" Back to List></a>
            </div>
        </div>
    </div>
</body>

Infinite.MVCCore.TaxiBooking/Views/Employees/Details.cshtml
@model EmployeeViewModel
@{
    ViewData["Title"] = "Details";
}
<style>
    .Details{

    }
</style>
<body class="Details">
   

    <div class="row offset-4">
        
        <div class="col-md-7">
            <h1 class=" p-5"> List Of Details</h1>
            <ul class="list-group">
                <li class="list-group-item"><b>Employee Name:</b>@Model.EmployeeName</li>
                @*<li class="list-group-item"><b>Designation Id:</b>@Model.DesignationId</li>*@
                <li class="list-group-item"><b>Designation Name:</b>@Model.DesignationName</li>
                <li class="list-group-item"><b>Phone Number:</b>@Model.PhoneNo</li>
                <li class="list-group-item"><b>Email Id:</b>@Model.EmailId</li>
                <li class="list-group-item"><b>Address:</b>@Model.Address</li>
                <li class="list-group-item"><b>DrivingLicenseNo:</b>@Model.DrivingLicenseNo</li>
            </ul>
            <br />
            <a asp-controller="Employees" asp-action="Index" class="btn btn-info"> Back To Index</a>
        </div>
    </div>
</body>

Infinite.MVCCore.TaxiBooking/Views/Employees/Edit.cshtml
@model EmployeeViewModel
@{
    ViewData["Title"] = "Edit";
}
<body>
    <div class="container offset-4 pt-5">
        <h1>Edit Employee</h1>

        <form asp-controller="Employees" asp-action="Edit" method="post">
            <div class="row">
                <div class="col-md-4">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="mb-2">
                        <label asp-for="EmployeeName" class="form-label"></label>
                        <input type="text" asp-for="EmployeeName" class="form-control" />
                        <span asp-validation-for="EmployeeName"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="DesignationId" class="form-label"></label>
                        <input type="text" asp-for="DesignationId" class="form-control" />
                        <span asp-validation-for="DesignationId"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="PhoneNo" class="form-label"></label>
                        <input type="text" asp-for="PhoneNo" class="form-control" />
                        <span asp-validation-for="PhoneNo"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="EmailId" class="form-label"></label>
                        <input type="text" asp-for="EmailId" class="form-control" />
                        <span asp-validation-for="EmailId"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="Address" class="form-label"></label>
                        <input type="text" asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="DrivingLicenseNo" class="form-label"></label>
                        <input type="text" asp-for="DrivingLicenseNo" class="form-control" />
                        <span asp-validation-for="DrivingLicenseNo"></span>
                    </div>
                    <div class="mb-2" d-grid>
                        <input type="submit" class="btn btn-primary w-100" value="Update Employee" />

                    </div>
                    <a asp-controller="Employees" asp-action="Index" Back to List></a>
                </div>
            </div>
        </form>
    </div>
</body>

Infinite.MVCCore.TaxiBooking/Views/Employees/Index.cshtml
@model IEnumerable<EmployeeViewModel>

@{
    ViewData["Title"] = "Index";
}
<style>
    .image {
        background-image: url('https://images.unsplash.com/photo-1556339979-d7548eaf2401?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80');
        background-repeat: no-repeat;
        background-size: cover;
    }
    .table{
        background-color:black;
    }
</style>

<body class="image">


    <div class="row offset-2 pt-5">
        @*<div class="col-md-9">*@
        <div class="row">
            <div class="col">
                <h2>List of Employees</h2>
            </div>
            <div class="col">
                <a asp-controller="Employees" asp-action="Create" class="btn btn-primary">Create new Employee</a>
            </div>

        </div>

        <div class="col-md-9">
            <table class="table table-hover ">
                <thead>
                    <tr>
                        <th>Employee Id</th>
                        <th>Employee Name</th>
                       
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var x in Model)
                    {
                        <tr>
                            <td>@x.EmployeeId</td>
                            <td>@x.EmployeeName</td>
                            
                            <td>
                                <a asp-controller="Employees" asp-action="Details" asp-route-id="@x.EmployeeId" class="btn btn-primary">Details</a>
                                <a asp-controller="Employees" asp-action="Edit" asp-route-id="@x.EmployeeId" class="btn btn-primary">Edit</a>
                                <a asp-controller="Employees" asp-action="Delete" asp-route-id="@x.EmployeeId" class="btn btn-primary">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
        @*</div>*@
    </div>
    </body>

Infinite.MVCCore.TaxiBooking/Views/Employees/Landing.cshtml
@{
    ViewData["Title"] = "Landing";
}

<style>
   
    .bd {
        border-radius: 10px;
        width: 300px;
        height: 250px;
    }
    .btn{
        margin-left:15px;
        width:270px;
    }
</style>
<body class="body">
    <h1 class="text-white offset-5 pt-4">Landing</h1>
    <div class="row offset-2 pt-5 ">

        <div class=" col border-dark ">
            <div class="col">
                <img src="https://tse4.mm.bing.net/th/id/OIP.rC4ywFmsTivtRXamIk5rJQHaF2?pid=ImgDet&rs=1"class="bd w-90 " />
            </div>
            <br />
            <div class=" col">
                <a asp-controller="Bookings" asp-action="index" class="btn btn-danger">Booking Details</a>
            </div>
        </div>

        <div class=" col border-dark">
            <div class="col">
                <img src="~/Images/Employees(Admin).jpg" class="bd w-90" />
            </div>
            <br />
            <div class=" col">
                <a asp-controller="Admin" asp-action="EmployeeRoster" class="btn btn-danger ">Employee Roster Details</a>

            </div>
        </div>
        @*<div class=" col border-dark ">
            <div class="col">
                <img src="~/Images/Employees(Admin).jpg" class="bd w-90 " />
            </div>
            <br />
            <div class="col">
                <a asp-controller="Admin" asp-action="EmployeeRoster" class="btn btn-danger">EmployeeRoster Details</a>

            </div>
        </div>*@


    </div>
</body>