Infinite.MVCCore.TaxiBooking/Models/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Infinite.MVCCore.TaxiBooking.Models
{
    public class CustomerViewModel
    {
        public int CustomerId { get; set; }
        [Required(ErrorMessage ="Please provide name")]
        [Display(Name ="Customer Name")]
        public string CustomerName { get; set; }
        [Required(ErrorMessage ="Please provide Mobile Number")]
        [Phone]
        [Display(Name ="Mobile Number")]
        public string PhoneNo { get; set; }
        [Required(ErrorMessage ="Please provide Email Id")]
        [EmailAddress]
        [Display(Name ="Email Id")]
        public string EmailId { get; set; }
        [Required(ErrorMessage ="Please provide address")]
        public string Address { get; set; }
    }
}

Infinite.MVCCore.TaxiBooking/Controllers/AdminController.cs
using Infinite.MVCCore.TaxiBooking.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace Infinite.MVCCore.TaxiBooking.Controllers
{
    public class AdminController : Controller
    {
        public readonly IConfiguration _configuration;
        public IActionResult Index()
        {
            return View();
        }

        public AdminController( IConfiguration configuration)
        {
            _configuration= configuration;
        }

        public async Task<IActionResult> Customers()
        {

            List<CustomerViewModel> customers = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("Customers/GetAllCustomers");
                if (result.IsSuccessStatusCode)
                {
                    customers = await result.Content.ReadAsAsync<List<CustomerViewModel>>();
                }
            }
            return View(customers);
           
        }
        public async Task<IActionResult> Employees()
        {
            List<EmployeeViewModel> employees = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("Employees/GetAllEmployees");
                if (result.IsSuccessStatusCode)
                {
                    employees = await result.Content.ReadAsAsync<List<EmployeeViewModel>>();
                }
            }
            return View(employees);
        }
        public async Task<IActionResult> EmployeeRoster()
        {
            List<EmployeeRosterViewModel> employeeRosters = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("EmployeeRosters/GetAllRosters");
                if (result.IsSuccessStatusCode)
                {
                    employeeRosters = await result.Content.ReadAsAsync<List<EmployeeRosterViewModel>>();
                }
            }

            return View(employeeRosters);
           
        }
    }
}

Infinite.MVCCore.TaxiBooking/Controllers/CustomersController.cs
using Infinite.MVCCore.TaxiBooking.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace Infinite.MVCCore.TaxiBooking.Controllers
{
    public class CustomersController : Controller
    {
        public readonly IConfiguration _configuration;
        public CustomersController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Landing()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
            List<CustomerViewModel> customers = new();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("Customers/GetAllCustomers");
                if (result.IsSuccessStatusCode)
                {
                    customers = await result.Content.ReadAsAsync<List<CustomerViewModel>>();
                }
            }
            return View(customers);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            CustomerViewModel customer = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync($"Customers/GetCustomerById/{id}");
                if (result.IsSuccessStatusCode)
                {
                    customer = await result.Content.ReadAsAsync<CustomerViewModel>();
                }
            }
            return View(customer);
        }

        [HttpGet]
        [Route("Customers/Create")]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost("Customers/Create")]
        public async Task<IActionResult> Create(CustomerViewModel customer)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    
                    var result = await client.PostAsJsonAsync("Customers/CreateCustomer", customer);
                    if (result.StatusCode == System.Net.HttpStatusCode.Created)
                    {

                        return RedirectToAction("Index");
                    }
                }
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (ModelState.IsValid)
            {
                CustomerViewModel customer = null;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.GetAsync($"Customers/GetCustomerById/{id}");
                    if (result.IsSuccessStatusCode)
                    {
                        customer = await result.Content.ReadAsAsync<CustomerViewModel>();
                        return View(customer);
                    }
                    else
                    {
                        ModelState.AddModelError("", "Customer doesn't exist");
                    }

                }
            }
            return View();
        }

        [HttpPost]
        [Route("Customers/Edit/{CustomerId}")]
        public async Task<IActionResult> Edit(CustomerViewModel customer)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.PutAsJsonAsync($"Customers/UpdateCustomer/{customer.CustomerId}", customer);
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Server Error, Please try later");
                    }

                }
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            CustomerViewModel customer = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync($"Customers/GetCustomerById/{id}");
                if (result.IsSuccessStatusCode)
                {
                    customer = await result.Content.ReadAsAsync<CustomerViewModel>();
                    return View(customer);
                }
                else
                {
                    ModelState.AddModelError("", "Server Error.Please try later");
                }
            }
            return View(customer);
        }



        [HttpPost("Customers/Delete/{CustomerId}")]
        public async Task<IActionResult> Delete(CustomerViewModel customer)
        {
            
            using (var client = new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.DeleteAsync($"Customers/DeleteCustomer/{customer.CustomerId}");
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");

                }
                else
                {
                    ModelState.AddModelError("", "Server Error.Please try later");
                }
            }
            return View();

        }
    }
}

Infinite.MVCCore.TaxiBooking/Views/Customers/Create.cshtml
@model CustomerViewModel
@{
    ViewData["Title"] = "Create";
}
<div class="col offset-4 pt-5 ">
    <h1>Create Customer</h1>

    <form asp-controller="Customers" asp-action="Create" method="post">
        <div class="row">
            <div class="col-md-7">
                <div class="mb-2 ">
                    <label asp-for="CustomerName" class="form-label"></label>
                    <input type="text" asp-for="CustomerName" class="form-control" />
                    <span asp-validation-for="CustomerName"></span>
                </div>
                <div class="mb-2">
                    <label asp-for="PhoneNo" class="form-label"></label>
                    <input type="text" asp-for="PhoneNo" class="form-control" />
                    <span asp-validation-for="PhoneNo"></span>
                </div>
                <div class="mb-2">
                    <label asp-for="EmailId" class="form-label"></label>
                    <input type="text" asp-for="EmailId" class="form-control" />
                    <span asp-validation-for="EmailId"></span>
                </div>

                <div class="mb-2">
                    <label asp-for="Address" class="form-label"></label>
                    <input type="text" asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address"></span>
                </div>

                <div class="mt-2 d-grid">
                    <input type="submit" class="btn btn-primary" value="Add New" />

                </div>
            </div>
        </div>
    </form>
</div>

Infinite.MVCCore.TaxiBooking/Views/Customers/Delete.cshtml
@model CustomerViewModel
    @{
        ViewData["Title"] = "Delete";
    }
    <body>
        <div class="container offset-4 pt-5">
            <h1>Delete Customer</h1>

            <div class="row">
                <div class="col-md-5">
                    <div asp-validation-summary="All" class="text-danger"></div>

                    <ul class="list-group">
                        <li class="list-group-item"><b>CustomerName</b>@Model.CustomerName</li>
                        <li class="list-group-item"><b>PhoneNo</b>@Model.PhoneNo</li>
                        <li class="list-group-item"><b>EmailId</b>@Model.EmailId</li>
                        <li class="list-group-item"><b>Address</b>@Model.Address</li>

                    </ul>
                    <div>
                        Are you sure do you want to delete this Customer?
                    </div>
                    <div>
                        <form asp-controller="Customers" asp-action="Delete" method="post">
                            <button type="submit" class="btn btn-danger">Delete</button>
                            <a asp-controller="Customers" asp-action="Index" Back to List></a>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </body>

Infinite.MVCCore.TaxiBooking/Views/Customers/Details.cshtml
@model CustomerViewModel
@{
    ViewData["Title"] = "Details";
}
<body>
    <div class="container offset-4 pt-5">
        <h1>Details of Customer</h1>
        <div>
            <div class="row">
                <div class="col-md-5">
                    <ul class="list-group">
                        <li class="list-group-item"><b>Customer Id :</b>@Model.CustomerId</li>
                        <li class="list-group-item"><b>Customer Name :</b>@Model.CustomerName</li>
                        <li class="list-group-item"><b>Mobile Number :</b>@Model.PhoneNo</li>
                        <li class="list-group-item"><b>Email Id :</b>@Model.EmailId</li>
                        <li class="list-group-item"><b>Full Address :</b>@Model.Address</li>
                    </ul>
                    <a asp-controller="Customers" asp-action="Index">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</body>

Infinite.MVCCore.TaxiBooking/Views/Customers/Edit.cshtml
@model CustomerViewModel
@{
    ViewData["Title"] = "Edit";
}
<div class="col offset-4 pt-5 ">
    <h1>Edit Customer</h1>

    <form asp-controller="Customers" asp-action="Edit" method="post">
        <div class="row">
            <div class="col-md-6">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-2">
                    <label asp-for="CustomerName" class="form-label"></label>
                    <input type="text" asp-for="CustomerName" class="form-control" />
                    <span asp-validation-for="CustomerName"></span>
                </div>
                <div class="mb-2">
                    <label asp-for="PhoneNo" class="form-label"></label>
                    <input type="text" asp-for="PhoneNo" class="form-control" />
                    <span asp-validation-for="PhoneNo"></span>
                </div>
                <div class="mb-2">
                    <label asp-for="EmailId" class="form-label"></label>
                    <input type="text" asp-for="EmailId" class="form-control" />
                    <span asp-validation-for="EmailId"></span>
                </div>
                <div class="mb-2">
                    <label asp-for="Address" class="form-label"></label>
                    <input type="text" asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address"></span>
                </div>
                <div class="mt-2" d-grid>
                    <input type="submit" class="btn btn-primary" value="Update Customer" />
                </div>
            </div>
        </div>
    </form>
    </div>

Infinite.MVCCore.TaxiBooking/Views/Customers/Index.cshtml
@model IEnumerable<CustomerViewModel>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<style>
    .body {
        background-image: url("");
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>
<body class="body">
    <div class="row offset-2 pt-4">
        <div class="col-md-9">
           

            <table class="table table-hover border-2">
                <thead>
                    <tr>

                        <th scope="col">Customer Id</th>
                        <th scope="col">  </th>
                        <th scope="col">  </th>
                        <th scope="col">Custmer Name</th>
                        <th scope="col">  </th>
                        <th scope="col">  </th>
                        <th scope="col" class="offset-2">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {


                        <tr class="table-dark">

                            <td>@item.CustomerId</td>
                            <td> </td>
                            <td></td>
                            <td>@item.CustomerName</td>
                            <td> </td>
                            <td></td>
                            <td class="pl-3">
                                <a asp-controller="Customers" asp-action="Details" asp-route-id="@item.CustomerId" class="btn btn-light">Details</a>
                                <a asp-controller="Customers" asp-action="Edit" asp-route-id="@item.CustomerId" class="btn btn-primary">Edit</a>
                                <a asp-controller="Customers" asp-action="Delete" asp-route-id="@item.CustomerId" class="btn btn-danger">Delete</a>
                            </td>
                        </tr>

                    }
                </tbody>
            </table>
        </div>
    </div>
</body>

Infinite.MVCCore.TaxiBooking/Views/Customers/Landing.cshtml
@{
    ViewData["Title"] = "Landing";
}

<style>
  
    .bd {
        border-radius: 10px;
        width: 300px;
        height: 250px;
    }

    /*.btn {
        width: 270px;
    }*/
</style>
<body class="body">
    <h1 class="text-white offset-5 pt-4">Home </h1>
    <div class="row offset-2 pt-5 ">

        <div class=" col border-dark ">
            <div class="col">
                <img src="https://tse4.mm.bing.net/th/id/OIP.rC4ywFmsTivtRXamIk5rJQHaF2?pid=ImgDet&rs=1" class="bd w-90 " />
            </div>
            <br />
            <div class="col offset-2">
                <a asp-controller="Bookings" asp-action="Create" class="btn btn-danger">New Bookings</a>
            </div>
        </div>

        <div class="col border-dark">
            <div class="col">
                <img src="~/Images/Employees(Admin).jpg" class="bd w-90" />
            </div>
            <br />
            <div class="col offset-2">
                <a asp-controller="Bookings" asp-action="index" class="btn btn-danger ">Booking History</a>

            </div>
        </div>
        @*<div class=" col border-dark ">
                <div class="col">
                    <img src="~/Images/Employees(Admin).jpg" class="bd w-90 " />
                </div>
                <br />
                <div class="col">
                    <a asp-controller="Admin" asp-action="EmployeeRoster" class="btn btn-danger">EmployeeRoster Details</a>

                </div>
            </div>*@


    </div>
</body>